---
# c.f. https://github.com/theforeman/foreman-ansible-modules
# and the Plugin Index at https://theforeman.org/plugins/foreman-ansible-modules/
#
# Note that on this instance, my LCE Path is
# lce-soecitest2 → SOE Test → Engineering → Development → Quality Assurance → Simulation → Production
# hence my choices of `force_promote: …` and `auto_publish: …`.
# You should adjust those two to your needs.

# my Ansible control node connects to the Satellite server.
# Purely personal preference to run the tasks on my workstation.
- hosts: localhost

  # put your vars wherever is comforable for you, a Tower, an AWX, a file automatically picked up by Ansible, a file explicitly specified, in this playbook or a mix. Your call, choose what fits your environment best.
  vars_files:
    - '/home/pcfe/work/git/HouseNet/ansible/pcfe.net/vars/satellite-secrets.yml' # in my setup that file only contains `vaulted_sat6_pass: …`

  vars:
    sat_server_url:       'https://satellite.internal.pcfe.net'
    sat_username:         'admin'
    sat_password:         '{{ vaulted_sat6_pass }}'
    sat_org:              'Sat Test'
    product_jenkins:      'prd-jenkins'

  tasks:
    # If the key at https://pkg.jenkins.io/redhat-stable/jenkins.io.key changes,
    # then be sure to update your sha256sum in this task
    - name: 'Ensure we have a local copy of the GPG key jenkins.io.key'
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.io.key
        dest: /tmp/jenkins.io.key
        checksum: sha256:f6b8584841a7f2852ad9a00b8f8d53ba40bb2942c8d6b99d6bf30a4f48b0cf69

    # n.b.: you could also omit the previous get_url task and do something like
    # content: "{{ lookup('url', 'https://pkg.jenkins.io/redhat-stable/jenkins.io.key') }}"
    # Merci Zhenech.
    # but that will take away the check that the GPG key retrieved over https actually matches the checksum in this playbook
    - name: "Ensure Satellite knows the GPG key used to sign the Jenkins redhat-stable RPMs"
      theforeman.foreman.content_credential:
        username:     '{{ sat_username }}'
        password:     '{{ vaulted_sat6_pass }}'
        server_url:   '{{ sat_server_url }}'
        organization: '{{ sat_org }}'
        name:         'gpg-jenkins'
        content_type: gpg_key
        content:      "{{ lookup('file', '/tmp/jenkins.io.key') }}"

    - name: 'Ensure Product Jenkins exists'
      theforeman.foreman.product:
        username:     '{{ sat_username }}'
        password:     '{{ vaulted_sat6_pass }}'
        server_url:   '{{ sat_server_url }}'
        organization: '{{ sat_org }}'
        name:         '{{ product_jenkins }}'
        description:  'See https://jenkins.io/ for details'
        state:        present

    # do NOT use `auto_enabled:` until https://github.com/theforeman/foreman-ansible-modules/issues/975 is resolved
    - name: 'Ensure Jenkins Repository redhat-stable exists'
      theforeman.foreman.repository:
        username:     '{{ sat_username }}'
        password:     '{{ vaulted_sat6_pass }}'
        server_url:   '{{ sat_server_url }}'
        organization: '{{ sat_org }}'
        checksum_type:      sha256
        content_type:       yum
        download_policy:    immediate
        mirror_on_sync:     yes
        label:              jenkins-redhat-stable
        name:               jenkins-redhat-stable
        product:            '{{ product_jenkins }}'
        state:              present
        unprotected:        no
        url:                'http://pkg.jenkins-ci.org/redhat-stable/'
        verify_ssl_on_sync: 'yes'

# unfinished: add gpog key and define CV


